In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from  statsmodels.stats.weightstats import ttest_ind
from itertools import permutations, combinations
import scipy.stats as st

In [130]:
data = pd.read_csv('../data/sotnikov.ad_hw4.csv', header=None)

In [131]:
data.head()

0         1         2         3         4         5         6
0 -0.205596 -1.215910  1.081042 -0.394865  0.551866 -1.239099  3.286233
1 -0.716905 -1.351013 -1.707242 -0.681160 -0.229419 -0.193524  0.314508
2  0.687389 -1.848718 -0.047388 -0.528018 -0.442669 -0.862317  1.334345
3 -0.991881  0.064409 -0.834084 -1.195899  0.806054 -0.951557 -0.520300
4 -2.720189 -1.993786  0.703941 -2.937643  0.118609 -0.398863 -1.150798

In [132]:
data.describe()

0          1          2          3          4          5  \
count  30.000000  30.000000  30.000000  30.000000  30.000000  30.000000   
mean   -0.701458  -1.331023   0.475301  -0.934168   0.059500  -0.705366   
std     1.030555   0.870933   0.991702   0.981636   0.861762   0.982651   
min    -2.720189  -3.820915  -1.707242  -2.997195  -1.912362  -2.333580   
25%    -1.448247  -1.720042   0.029798  -1.442339  -0.458022  -1.545760   
50%    -0.635411  -1.380081   0.466465  -0.818275   0.222358  -0.985346   
75%    -0.208946  -0.821177   1.112126  -0.347125   0.626385  -0.127606   
max     1.344145   0.213012   2.582006   1.251732   1.842147   1.782408   

               6  
count  30.000000  
mean    1.058050  
std     1.058005  
min    -1.150798  
25%     0.273290  
50%     0.993464  
75%     1.608570  
max     3.711286

In [133]:
data.shape[1]

7

In [134]:
vombo = combinations(list(data.columns), 2)
for x, y in vombo:
    print(x, y)

0 1
0 2
0 3
0 4
0 5
0 6
1 2
1 3
1 4
1 5
1 6
2 3
2 4
2 5
2 6
3 4
3 5
3 6
4 5
4 6
5 6


#### 1) Воспользуемся t-критерем для сравнения средних для всех пар столбцов из выборки. Для какого количества пар столбцов отвергается гипотеза о совпадении среднего?

In [135]:
x = []
for i in range(data.shape[1]):
    x.append(list(data[i]))

In [136]:
column_pairs = 0
vombo = combinations(list(data.columns), 2)

for first, second in vombo:
    if st.ttest_ind(x[first], x[second])[1] <= 0.05:
        column_pairs += 1
print(column_pairs)

16


Получаем 16 cnолбцов

#### 2) Значение уровня значимости при введении поправки Бонферрони (alpha=0.05). Округлить до 3 знака после запятой

In [137]:
p_values = []
vombo = combinations(list(data.columns), 2)
for first, second in vombo:
    p_values.append(st.ttest_ind(x[first], x[second])[1])

In [138]:
from statsmodels.stats.multitest import multipletests
p_adjusted = multipletests(p_values, alpha=0.05, method='bonferroni')

In [139]:
p_adjusted

(array([False,  True, False, False, False,  True,  True, False,  True,
        False,  True,  True, False,  True, False,  True, False,  True,
         True,  True,  True]),
 array([2.78106850e-01, 6.81966518e-04, 1.00000000e+00, 6.22144456e-02,
        1.00000000e+00, 3.84541451e-07, 9.02577177e-09, 1.00000000e+00,
        1.25617098e-06, 2.41645548e-01, 3.50465871e-12, 1.66400564e-05,
        1.00000000e+00, 4.39360152e-04, 6.66186215e-01, 2.18794104e-03,
        1.00000000e+00, 7.03124663e-09, 4.60919449e-02, 3.71504664e-03,
        2.04499598e-07]),
 0.002439557259668823,
 0.002380952380952381)

In [140]:
round(p_adjusted[-1], 3)

0.002

#### 3) Для какого количества пар столбцов отвергается гипотеза о совпадении среднего при использовании поправки Бонферрони? 

In [141]:
p_adjusted

(array([False,  True, False, False, False,  True,  True, False,  True,
        False,  True,  True, False,  True, False,  True, False,  True,
         True,  True,  True]),
 array([2.78106850e-01, 6.81966518e-04, 1.00000000e+00, 6.22144456e-02,
        1.00000000e+00, 3.84541451e-07, 9.02577177e-09, 1.00000000e+00,
        1.25617098e-06, 2.41645548e-01, 3.50465871e-12, 1.66400564e-05,
        1.00000000e+00, 4.39360152e-04, 6.66186215e-01, 2.18794104e-03,
        1.00000000e+00, 7.03124663e-09, 4.60919449e-02, 3.71504664e-03,
        2.04499598e-07]),
 0.002439557259668823,
 0.002380952380952381)

In [142]:
p_adjusted[0].sum()

12

#### 4) Для какого количества пар столбцов отвергается гипотеза о совпадении среднего при использовании метода Холма?

In [143]:
p_adjusted = multipletests(p_values, alpha=0.05, method='holm')

In [144]:
p_adjusted

(array([False,  True, False,  True, False,  True,  True, False,  True,
        False,  True,  True, False,  True, False,  True, False,  True,
         True,  True,  True]),
 array([9.27022833e-02, 4.22169749e-04, 1.00000000e+00, 2.66633338e-02,
        1.00000000e+00, 3.11295460e-07, 8.16617446e-09, 4.41643022e-01,
        9.57082655e-07, 9.20554469e-02, 3.50465871e-12, 1.18857546e-05,
        4.41643022e-01, 2.92906768e-04, 1.90338919e-01, 1.25025202e-03,
        1.00000000e+00, 6.69642536e-09, 2.19485452e-02, 1.94597681e-03,
        1.75285370e-07]),
 0.002439557259668823,
 0.002380952380952381)

In [145]:
p_adjusted[0].sum()

13

#### 5) Оценка m0 по методу Шведера-Спьётволла (lambda = 0.5)

In [146]:
def hujna(p_values, lambda_=0.5):
    return (1/(1-lambda_) * (1+sum(map(lambda x: 1 if x > lambda_ else 0, p_values))))    

In [147]:
hujna(p_values)

4.0